In [1]:
import sklearn as sk
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, precision_recall_fscore_support
from pylab import plot, plt

In [61]:
data = pd.read_csv("Final Data.csv")

In [66]:
# data.drop(columns="SEQN", inplace=True)
# data["TELOMEAN"]= data["TELOMEAN"].astype(int)
data["Weight H.BMI"] = data["Weight H.BMI"].fillna(0.0).astype(int)


In [205]:
data

TELOMEAN  Weight H.BMI SMQ.SMQ040 SMQ.SMD075 PA.PAQ180 PA.PAQ520  \
0         6699            20          3          0         1         3   
1         5468            23          3          0         3         3   
2         6414            30          3          0         1         3   
3         5190            20          3          0         1         3   
4         6885            30          3          0         2         2   
5         6262            24          3          0         3         3   
6         5881            23          3          0         2         3   
7         6222            26          3          0         2         3   
8         7487            21          3          0         2         3   
9         6281            27          3          0         2         3   
10        6353            19          3          0         1         1   
11        6146            29          3          0         3         1   
12        5953            18          3          0         3         3   
13        6273            24          1          1         2         3   
14        6048            19          1          1         3         3   
15        6101            20          1          1         3         3   
16        6601            22          1          2         3         3   
17        5672            21          1          2         2         3   
18        6318            20          1          2         2         3   
19        5386            19          1          2         2         3   
20        5729            30          1          2         2         3   
21        5051            18          1          3         2         3   
22        8393            18          1          3         2         1   
23        6440            21          1          3         2         3   
24        5013            33          1          3         2         3   
25        6352            21          1          4         2         2   
26        6119            20          1          4         2         2   
27        5320            22          1          5         2         1   
28        6355            24          1          5         3         3   
29        6748            33          1          5         4         3   
...        ...           ...        ...        ...       ...       ...   
1719      5732            25          3          0         4         1   
1720      4699            26          3          0         2         2   
1721      5959            32          3          0         1         3   
1722      5070            31          3          0         1         1   
1723      5452            20          3          0         2         1   
1724      5027            37          3          0         2         2   
1725      5840            35          3          0         2         3   
1726      5793            35          3          0         3         2   
1727      5562            20          3          0         3         1   
1728      6453            25          3          0         2         1   
1729      5184            21          3          0         2         1   
1730      5636            27          3          0         1         3   
1731      6668            24          3          0         2         3   
1732      5083            24          3          0         2         1   
1733      5663            28          3          0         2         3   
1734      5079            33          3          0         2         3   
1735      6524            26          3          0         2         3   
1736      6090            31          1          1         1         2   
1737      4708            25          1          2         4         1   
1738      5374            26          1         10         1         2   
1739      6196            34          2         10         2         1   
1740      4885            27          1         10         2         1   
1741      

In [101]:
print(type(data["TELOMEAN"]), type(data["Weight H.BMI"][0]),
      type(data["SMQ.SMQ040"][0]), '\n',type(data["SMQ.SMD075"][0]),
      type(data["PA.PAQ180"][0]), type(data["PA.PAQ520"][0]), '\n',
      type(data["DU.DUQ100"][0]), type(data["ALQ.ALQ130"][0]),
      type(data["Gender and Age.RIAGENDR"][0]), '\n', type(data["Gender and Age.RIDAGEYR"][0]))

<class 'pandas.core.series.Series'> <class 'numpy.int64'> <class 'str'> 
 <class 'str'> <class 'str'> <class 'str'> 
 <class 'str'> <class 'numpy.int64'> <class 'str'> 
 <class 'numpy.int64'>


In [97]:
data["SMQ.SMQ040"] = data["SMQ.SMQ040"].astype(str)

In [234]:
data["SMQ.SMD075"] = data["SMQ.SMD075"].astype(int)
data["PA.PAQ180"] = data["PA.PAQ180"].astype(str)
data["PA.PAQ520"] = data["PA.PAQ520"].astype(str)
data["DU.DUQ100"] = data["DU.DUQ100"].astype(str)
data["Gender and Age.RIAGENDR"] = data["Gender and Age.RIAGENDR"].astype(str)

In [235]:
data["SMQ.SMD075"]= pd.Categorical(data["SMQ.SMD075"])
data["PA.PAQ180"] = pd.Categorical(data["PA.PAQ180"])
data["PA.PAQ520"] = pd.Categorical(data["PA.PAQ520"])
data["DU.DUQ100"] = pd.Categorical(data["DU.DUQ100"])
data["Gender and Age.RIAGENDR"] = pd.Categorical(data["Gender and Age.RIAGENDR"])

In [236]:
type(data["DU.DUQ100"][0])

str

### PolyFit

In [188]:
age = data["Gender and Age.RIDAGEYR"]
length = data["TELOMEAN"]

In [201]:
# data["Gender and Age.RIDAGEYR"] = data["Gender and Age.RIDAGEYR"].astype(int)

z= np.polyfit(age,length,5)
# type(data["TELOMEAN"][0])
np.poly1d(z)(58)

5622.354924701775

In [ ]:
from sklearn.preprocessing import OneHotEncoder, LabelEncoder

In [442]:
data_man = data.loc[data["Gender and Age.RIAGENDR"]=='1']
data_man.drop(columns=["Gender and Age.RIAGENDR"])
data_woman = data.loc[data["Gender and Age.RIAGENDR"]=='2']
data_woman.drop(columns=["Gender and Age.RIAGENDR"])


TELOMEAN  Weight H.BMI SMQ.SMQ040 SMQ.SMD075 PA.PAQ180 PA.PAQ520  \
0         6699            20          3          0         1         3   
2         6414            30          3          0         1         3   
3         5190            20          3          0         1         3   
4         6885            30          3          0         2         2   
6         5881            23          3          0         2         3   
8         7487            21          3          0         2         3   
9         6281            27          3          0         2         3   
12        5953            18          3          0         3         3   
16        6601            22          1          2         3         3   
21        5051            18          1          3         2         3   
22        8393            18          1          3         2         1   
26        6119            20          1          4         2         2   
30        5596            27          1          5         3         2   
37        5984            21          2         10         2         3   
38        6634            24          2         10         2         1   
39        7381            23          2         10         2         3   
43        6332            28          3          0         1         2   
44        6952            25          3          0         2         3   
45        5359            27          3          0         2         3   
46        5529            26          3          0         1         2   
52        5966            21          1          1         2         1   
53        6304            23          1          1         2         1   
55        6504            21          1          2         3         3   
56        6441            26          1          2         2         3   
57        6523            21          1          2         2         1   
59        6299            24          1          2         2         3   
62        6255            32          1          2         3         2   
65        6686            31          1          3         2         2   
71        5845             0          1          4         3         2   
72        5396            20          1          5         2         3   
...        ...           ...        ...        ...       ...       ...   
1666      4880            29          3          0         2         3   
1667      4854            26          3          0         1         1   
1670      5546            24          3          0         2         1   
1673      6087            29          3          0         2         3   
1680      5199            29          3          0         1         3   
1682      5860            24          3          0         3         3   
1686      6323            21          1          6         2         1   
1690      5687            33          1         35         1         3   
1691      5036            32          1         37         1         2   
1693      5754            22          1         41         3         3   
1695      6135            26          3          0         3         1   
1696      5135            21          3          0         2         1   
1697      5900            26          3          0         2         1   
1702      5205            32          3          0         2         2   
1704      6068            24          3          0         3         1   
1705      5741            24          3          0         3         1   
1707      5832            31          3          0         2         3   
1711      4825            23          1          1         2         1   
1712      5587            38          1          2         1         2   
1715      6006            21          1         20         2         3   
1722      5070            31          3          0         1         1   
1723      5452            20          3          0         2         1   
1724      

In [443]:
cat_man = data_man[["SMQ.SMQ040","PA.PAQ180","PA.PAQ520"]].astype(str)
int_man = data_man[["Weight H.BMI","SMQ.SMD075","ALQ.ALQ130","Gender and Age.RIDAGEYR"]].astype(int)
cat_man, int_man

(     SMQ.SMQ040 PA.PAQ180 PA.PAQ520
 1             3         3         3
 5             3         3         3
 7             3         2         3
 10            3         1         1
 11            3         3         1
 13            1         2         3
 14            1         3         3
 15            1         3         3
 17            1         2         3
 18            1         2         3
 19            1         2         3
 20            1         2         3
 23            1         2         3
 24            1         2         3
 25            1         2         2
 27            1         2         1
 28            1         3         3
 29            1         4         3
 31            1         4         3
 32            1         2         3
 33            1         1         3
 34            2         2         3
 35            2         3         1
 36            2         3         3
 40            2         2         3
 41            2         3         3
 

In [355]:
categoricals = data[["SMQ.SMQ040","PA.PAQ180","PA.PAQ520","Gender and Age.RIAGENDR"]].astype(str)
integers = data[["Weight H.BMI","SMQ.SMD075","ALQ.ALQ130","Gender and Age.RIDAGEYR"]].astype(int)
categoricals, integers

(     SMQ.SMQ040 PA.PAQ180 PA.PAQ520 Gender and Age.RIAGENDR
 0             3         1         3                       2
 1             3         3         3                       1
 2             3         1         3                       2
 3             3         1         3                       2
 4             3         2         2                       2
 5             3         3         3                       1
 6             3         2         3                       2
 7             3         2         3                       1
 8             3         2         3                       2
 9             3         2         3                       2
 10            3         1         1                       1
 11            3         3         1                       1
 12            3         3         3                       2
 13            1         2         3                       1
 14            1         3         3                       1
 15            1        

In [356]:
le = LabelEncoder()
# data["SMQ.SMQ040"] = train_df["country"].astype('category',categories=["australia","germany","korea","russia","japan"])
enc = OneHotEncoder(categorical_features=["SMQ.SMQ040"])
categorical_2 = categoricals.apply(le.fit_transform).astype(str)
categorical_2.shape

(1749, 4)

In [357]:
categorical_2.values

array([['2', '0', '2', '1'],
       ['2', '2', '2', '0'],
       ['2', '0', '2', '1'],
       ...,
       ['0', '1', '1', '1'],
       ['0', '0', '2', '0'],
       ['0', '1', '0', '0']], dtype=object)

In [358]:
data_4 = pd.concat([categorical_2,integers],axis=1)

In [359]:
X_4 = data_4.values

In [360]:
y_4 = data.TELOMEAN.values

In [361]:
data_4.values[0]
# type(data_2.values[0][5])

array(['2', '0', '2', '1', 20, 0, 3, 20], dtype=object)

In [148]:
full_data_2 = data_2.values

In [149]:
y_2=full_data_2[:,0]
X_2=full_data_2[:,1:]

In [204]:
X_2, y_2

(array([[ 6,  2,  0, ...,  2,  1,  0],
        [ 9,  2,  0, ...,  3,  0,  0],
        [16,  2,  0, ...,  5,  1,  0],
        ...,
        [21,  0, 31, ...,  0,  1, 39],
        [12,  0, 33, ...,  1,  0, 39],
        [ 5,  0, 36, ...,  1,  0, 39]]),
 array([1050,  328,  941, ...,  554,  157,  715]))

In [140]:
X[0]

array([20, '3', '0', '1', '3', '2', 0, 3, '2', 20], dtype=object)

In [152]:
type(X_2[1][1])

numpy.int64

------------
### Logistic Regression

In [362]:
lr = LogisticRegression()
lr.fit_transform(X_4,y_4)

/Users/ekremguzelyel/anaconda/lib/python3.6/site-packages/sklearn/utils/deprecation.py:70: DeprecationWarning: Function transform is deprecated; Support to use estimators as feature selectors will be removed in version 0.19. Use SelectFromModel instead.
  warnings.warn(msg, category=DeprecationWarning)
/Users/ekremguzelyel/anaconda/lib/python3.6/site-packages/sklearn/utils/__init__.py:54: FutureWarning: Conversion of the second argument of issubdtype from `int` to `np.signedinteger` is deprecated. In future, it will be treated as `np.int64 == np.dtype(int).type`.
  if np.issubdtype(mask.dtype, np.int):


array([[2., 0., 2., 1., 3.],
       [2., 2., 2., 0., 4.],
       [2., 0., 2., 1., 6.],
       ...,
       [0., 1., 1., 1., 1.],
       [0., 0., 2., 0., 2.],
       [0., 1., 0., 0., 2.]])

In [363]:
predicts=lr.predict(X_4)

In [364]:
lr.score(X_4,y_4)
# predicts

0.10405946255002858

In [365]:
mean_squared_error(predicts,y_4)

510016.02801600914

-----------
### Trying Linear Regression

In [366]:
from sklearn.linear_model import LinearRegression

In [367]:
liR= LinearRegression()
liR.fit(X_4, y_4)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [368]:
pred = liR.predict(X_4)

In [369]:
mean_squared_error(pred,y_4)

379808.21171145444

------------------------
### Trying SVMs

In [370]:
from sklearn.svm import SVC

In [401]:
x_train, x_test, y_train, y_test = train_test_split(X_4, y_4,test_size=1/3)
len(x_train), len(x_test)

(1166, 583)

In [402]:
svc = SVC(gamma='auto', class_weight='balanced')
svc.fit(x_train, y_train) 

SVC(C=1.0, cache_size=200, class_weight='balanced', coef0=0.0,
  decision_function_shape=None, degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [403]:
pres = svc.predict(x_test)
mean_squared_error(pres, y_test)

749773.0943396227

In [373]:
pres[0:10]

array([6699, 6187, 6414, 6699, 6885, 6262, 5881, 6222, 5190, 6281])

In [271]:
X_3[0]

array([2, 0, 2, 1, 1, 20, '0', 0, 3, 20], dtype=object)

In [445]:
svc.predict(['0','0','1','0',20,0,10,59])

/Users/ekremguzelyel/anaconda/lib/python3.6/site-packages/sklearn/utils/validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


array([5562])

#### Telomere Means

In [330]:
# data.where(data["Gender and Age.RIDAGEYR"]==20)
lst=[]
for i in range(20,60):
    data_20= data.loc[data["Gender and Age.RIDAGEYR"]==i]
    lst.append((i, data_20.TELOMEAN.mean()))
lst    

[(20, 6185.186046511628),
 (21, 6264.086956521739),
 (22, 6235.04347826087),
 (23, 6254.45652173913),
 (24, 6029.365853658536),
 (25, 5988.285714285715),
 (26, 6111.454545454545),
 (27, 6158.975609756098),
 (28, 6014.760869565217),
 (29, 6084.976190476191),
 (30, 5859.510638297872),
 (31, 5955.692307692308),
 (32, 5982.454545454545),
 (33, 5858.421052631579),
 (34, 5908.621621621622),
 (35, 6061.0),
 (36, 5970.4),
 (37, 5685.8983050847455),
 (38, 6143.897959183673),
 (39, 5859.810344827586),
 (40, 5800.115384615385),
 (41, 5887.510638297872),
 (42, 5918.530612244898),
 (43, 5695.974358974359),
 (44, 5832.233333333334),
 (45, 5759.040816326531),
 (46, 5718.771929824561),
 (47, 5850.15),
 (48, 5811.8536585365855),
 (49, 5677.051282051282),
 (50, 5909.108695652174),
 (51, 5703.169811320755),
 (52, 5722.5),
 (53, 5658.9473684210525),
 (54, 5740.979166666667),
 (55, 5741.0),
 (56, 5616.0),
 (57, 5714.793103448276),
 (58, 5562.125),
 (59, 5598.333333333333)]

In [334]:
file = open("telomere_len_mean.txt","w") 
for i in lst:
    file.write(str(i[0])+" "+str(i[1])+"\n")
file.close() 

In [344]:
lst2=[]
for i in range(20,60):
    data_20= data.loc[data["Gender and Age.RIDAGEYR"]==i].loc[data["Gender and Age.RIAGENDR"]=='2']
    lst2.append((i, data_20.TELOMEAN.mean()))
lst2   

[(20, 6409.3125),
 (21, 6223.95),
 (22, 6131.740740740741),
 (23, 6514.368421052632),
 (24, 5996.125),
 (25, 5999.684210526316),
 (26, 6208.8),
 (27, 6070.666666666667),
 (28, 6035.25),
 (29, 5878.555555555556),
 (30, 5792.391304347826),
 (31, 5873.954545454545),
 (32, 6146.068965517241),
 (33, 5725.8),
 (34, 5835.444444444444),
 (35, 6142.8421052631575),
 (36, 5925.0625),
 (37, 5688.625),
 (38, 6211.0),
 (39, 5919.925925925926),
 (40, 5891.5),
 (41, 5880.875),
 (42, 5908.523809523809),
 (43, 5732.6),
 (44, 5931.827586206897),
 (45, 5822.347826086957),
 (46, 5681.894736842105),
 (47, 5821.578947368421),
 (48, 5838.2),
 (49, 5582.545454545455),
 (50, 6026.4375),
 (51, 5757.5),
 (52, 5746.35294117647),
 (53, 5718.625),
 (54, 6174.466666666666),
 (55, 5670.5),
 (56, 5542.25),
 (57, 5522.6),
 (58, 5643.4),
 (59, 5508.4)]

In [345]:
file = open("telomere_woman_mean.txt","w") 
for i in lst2:
    file.write(str(i[0])+" "+str(i[1])+"\n")
file.close() 

-------------

In [352]:
c=[2.5,3,5]
# mse=[]
for i in c:
    svc = SVC(gamma='auto',C=i)
    svc.fit(X_4, y_4) 
    pres = svc.predict(X_4)
    mse.append(mean_squared_error(pres, y_4))
    print(i)

2.5
3
5


In [353]:
mse

[528891.5328759291,
 528891.5328759291,
 246895.12578616352,
 111012.75586049171,
 77844.36420811893,
 40323.12349914237,
 9966.696397941681,
 8370.435677530017]